### ISSUE TITLE
DeprecationWarning: pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by chbndrhnns** [peopledoc/vault-cli#211]
I see this warning when running my tests:

```
../../../../Library/Caches/pypoetry/virtualenvs/xxx-sT27uenX-py3.9/lib/python3.9/site-packages/vault_cli/metadata.py:5
  /Users/cleancoder/Library/Caches/pypoetry/virtualenvs/xxx-sT27uenX-py3.9/lib/python3.9/site-packages/vault_cli/metadata.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources
```

**Comment by weakcamel** [comment]
As of March 2026, this is no longer a warning. With setuptools 82, vault-cli just crashes:

```
Traceback (most recent call last):
  File "/Users/myuser/git/config/.venv/bin/vault-cli", line 4, in <module>
    from vault_cli.cli import main
  File "/Users/myuser/git/config/.venv/lib/python3.13/site-packages/vault_cli/__init__.py", line 1, in <module>
    from vault_cli import metadata
  File "/Users/myuser/git/config/.venv/lib/python3.13/site-packages/vault_cli/metadata.py", line 5, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```
