### ISSUE TITLE
SyntaxError on every command

### ISSUE THREAD

**Issue by tlehoux** [peopledoc/vault-cli#54]
```
tlehoux@mymachine:~$ vault list
Traceback (most recent call last):
  File "/usr/local/bin/vault", line 7, in <module>
    from vault_cli.cli import main
  File "/var/<somewhere>/vault_cli/lib/python3.5/site-packages/vault_cli/__init__.py", line 19, in <module>
    from vault_cli.client import VaultAPIException, get_client
  File "/var/<somewhere>/vault_cli/lib/python3.5/site-packages/vault_cli/client.py", line 89
    client_class: Type[VaultClientBase]
                ^
SyntaxError: invalid syntax
```

```
tlehoux@mymachine:~$ cat /etc/debian_version
9.4
``` 

the python version
```➜  peoplecare git:(master) ✗ python
Python 2.7.15 (default, Jun 17 2018, 12:46:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.``` 

As a result, no more release is possible for our project.

**Comment by ewjoachim** [comment]
Yes, vault-cli is now Py3.6+. This has temporarly been solved by pinning a version that was compatible with py2.7, and will be solved in a better way by making python3.6 available on the machines you want to use vault-cli on.
